ory/cli

CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/bb146082236a7bbb94c3e042951b937aa76d25a4.
=> chore: update repository template to bb146082

cmd/dev/ci/monorepo/run.go, cmd/dev/ci/monorepo/run_test.go
Normally the command specified for 
```
ory dev ci monorepo run -c "echo hello" -m current_changed
```
are only executed if (in the example above the component in the current directory is changed. For our CircleCI case it would be beneficial to halt the current job, if the current component is not changed, affected or involved. 
Introduce a flag `--inverse` which will execute the commands if the component is not changed/affected/involved.
```
ory dev ci monorepo run -c "circleci-agent step halt" -m current_involved --inverse
```
In this example we would halt the CircleCI  job if the current component is not involved. …
=> feat: inverse mode

cmd/dev/pop/migration/fizzx/file_migrator.go
the changes.
works.
appropriate).
=> fix: append trailing comma only when missing

cmd/dev/schema/render_version.go, cmd/dev/schema/render_version_test.go
With go1.16 embed the config schemas are not in one conform place anymore.
=> fix: add schema path parameter to dev render version schema

cmd/dev/newsletter/stub/changelog.html.expected, view/mail-body.html
observation: the newsletter pointed to [ory/jobs](https://github.com/ory/jobs) 
fix: the newsletter now points to our dedicated [jobs page](https://www.ory.sh/jobs/)
=> fix: update url of 'we are hiring' section

cmd/cloud/proxy/common.go, cmd/cloud/proxy/proxy_local.go, cmd/cloud/proxy/proxy_production.go
BREAKING CHANGES: This patch adds logout capabilities and improved redirection handling. To achieve that we have changed a few things:
- The JSON Web Keys to validate Ory Proxy's JSON Web Tokens has moved from `/.ory/jwks.json` to `/.ory/proxy/jwks.json`.
- `ory proxy production` previously required a host to be specified (e.g. `example.org:1234`). From now on, you must specify a URL (e.g. `https://example.org:1234`).
Additionally, the `--protect-path-prefix` flag has been removed. We originally introduced this flag to get started easily. Defining policies on what should be protected and what not can however become quite complex. From regular expressions, to glob matching, to exclusions. This clashed with our vision of a simple to use CLI. Therefore, this feature has been removed.
Please …
=> feat: add better redirect and logout functionality

.github/workflows/stale.yml, npm/index.js
Updated repository templates to https://github.com/ory/meta/commit/e424c0a0a2dd85c585c0be32e8ada257c3fe8021.
=> chore: update repository template to e424c0a0

.github/workflows/ci.yaml
Adds Dockerhub credentials as inputs. Requires secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD`.
=> ci: add docker creds as inputs

.github/workflows/ci.yaml
The production `newsletter-send` workflow was using the wrong env var for the ssh key.
=> fix: use ORY_BOT_SSH_KEY

.github/workflows/ci.yaml
Switch to ory/ci/docs/cli-next for docs generation.
=> ci: use ory/ci/docs/cli-next for docs generation

cmd/cloudx/proxy/cmd_proxy.go, cmd/cloudx/proxy/cmd_proxy_test.go
the changes.
works.
appropriate).
=> chore: fix typo

cmd/dev/headers/license.go, cmd/dev/headers/license_test.go
Data is not protected by copyright law. YML files contain data. JSON also doesn't allow comments so this is more consistent.
the changes.
works.
appropriate).
=> fix: no license headers in YML files

cmd/dev/headers/license.go, cmd/dev/headers/license_test.go
Adds the ability to not add license headers to files in particular folders.
https://github.com/ory/hydra/pull/3216#issuecomment-1242660359
the changes.
works.
appropriate).
=> chore: folders without license headers

cmd/dev/headers/license.go, cmd/dev/headers/license_test.go
Don't add license headers to files in the node_modules and vendor folders.
https://github.com/ory-corp/general/issues/602
the changes.
works.
appropriate).
=> feat: license headers default ignore folders

cmd/cloudx/proxy/cmd_proxy.go, cmd/cloudx/proxy/proxy.go
This commit enables users to rewrite the Host header to the upstream host, rather than keeping it as the ory proxy Host.
This is especially useful in a scenario where the output of the tunnel routes based on Host.
- Custom endpoint per-user.
- Multiple service running behind a single load balancer
the changes.
works. (netcat and my staging env says it works)
appropriate).
=> feat: [cli/proxy] rewite-host flag

cmd/dev/headers/license.go
Fix path issues for license headers.
https://github.com/ory-corp/general/issues/602
the changes.
works.
appropriate).
=> fix: license headers ignore files

cmd/dev/headers/license.go
Don't add license header to prettier-ignored files.
https://github.com/ory-corp/general/issues/602
the changes.
works.
appropriate).
=> feat: license headers ignore prettier-ignored files

cmd/dev/release/publish.go
the changes.
works.
appropriate).
=> feat: allow release based on git hash

README.md
Other shells like Fish shell cannot execute the existing installation instructions because they rely on Bashisms. This PR introduces a simplified format for Ory CLI that is more compatible with different shells.
the changes.
works.
appropriate).
=> fix: installation instructions that are compatible with non-bash shells

cmd/dev/headers/comments/files_test.go, cmd/dev/headers/comments/formats_test.go
This makes tests immune to having their test data removed by the license header tool.
=> chore: simplify tests

cmd/dev/headers/comments/files_test.go, cmd/dev/headers/comments/formats.go
Prettifier removes the empty line between comments in TS and code. This caused the license header feature to eat some code.
=> chore: correctly handle license headers in TS files

cmd/dev/headers/copyright.go, cmd/dev/headers/copyright_test.go
Makes the tests for the copyright header functionality more isolated and self-describing.
=> chore: refactor copyright header tests

cmd/cloudx/client/handler.go, cmd/cloudx/project/update.go
When no `--file` flag is defined, the CLI will now read JSON from STDIN for project config updates.
=> feat: update config though STDIN

Makefile
A problem with the way the Makefile currenly installs external dependencies is that each time any change happens in the Makefile, it re-installs all dependencies. This gets annoying in repos that see a lot of changes to their Makefiles. This PR installs dependencies only when really needed, i.e. when they aren't installed or when their required version changes.
the changes.
works.
appropriate).
=> chore: persistent dependency installation

cmd/dev/headers/comments/files.go, cmd/dev/headers/comments/files_test.go, cmd/dev/headers/comments/formats.go, cmd/dev/headers/comments/formats_test.go, cmd/dev/headers/copyright.go, cmd/dev/headers/copyright_test.go
Deactivates updating an already existing copyright header with a different year.
The year should denote the year of original publication.
the changes.
works.
appropriate).
=> fix: dont update existing headers with new year

cmd/cloudx/client/client.go, cmd/cloudx/client/handler.go, cmd/cloudx/client/handler_test.go, cmd/cloudx/project/update_namespace_config.go
This PR enables supplying slugs to `cmd subcmd project PROJECTORSLUG` / `cmd ls identities PROJECTORSLUG`.
closes #267 
closes #156
the changes.
works.
appropriate).
=> feat: project flag accepts slug

npm/index.js
Add configuration to allow the npm package to work on linux-arm64
Installing or trying to use the ory cli via npm fails on arm64 linux, even though a binary is available. This PR fixes it.
the changes.
works.
appropriate).
=> fix: add linux-arm64 binary config into npm

.github/workflows/cve-scan.yaml
the changes.
works.
appropriate).
=> chore: add upload and output of sarif report

cmd/cloudx/proxy/proxy.go
Relates to issue #144. Being able to lookup the signing key by the key ID is very helpful when using a keystore. This change was originally accepted in PR #145 but was (accidentally?) dropped during some later code reshuffling.
the changes.
works.
appropriate).
=> Add key ID to JWT header

cmd/cloudx/client/auth.go, cmd/cloudx/client/command_helper_test.go, cmd/cloudx/client/config.go, cmd/root.go
With this change, refreshed tokens are now stored in the config.
We might need to handle the case where the refresh token expired more gracefully?
=> feat: store refreshed tokens

cmd/cloudx/accountexperience/accountexperience_test.go, cmd/cloudx/client/auth.go, cmd/cloudx/client/command_helper.go, cmd/cloudx/client/command_helper_test.go, cmd/cloudx/client/sdks.go, cmd/cloudx/identity/main_test.go, cmd/cloudx/oauth2/client_test.go, cmd/cloudx/organizations/organizations_test.go, cmd/cloudx/project/list_test.go, cmd/cloudx/project/main_test.go, cmd/cloudx/project/patch_test.go, cmd/cloudx/testhelpers/testhelpers.go, cmd/cloudx/testhelpers/testmain.go
Since we added OAuth2 login, we still used session tokens for some tests. This now eliminates that usage, ensuring that all endpoints work with OAuth2 access tokens (still found one during this PR).
=> test: always use OAuth2 token instead of session token

cmd/cloudx/client/auth.go
This fixes a timing issue where the CLI can finish the login and closes the callback server before the browser has been redirected and the user sees this instead of being sent to the console with the success message
=> fix: redirect user before finalizing OAuth2 login

cmd/cloudx/proxy/helpers.go
When using non standard headers in proxy requests, it results in error like
```
Preflight aborted: headers 'traceparent' not allowed
```
With this change you can specify additional headers to allow.
https://github.com/ory/cli/issues/261
the changes.
works.
appropriate).
=> feat: proxy flag for additional cors headers

.goreleaser.yml, cmd/dev/release/publish.go
This prevents deprecation notices from failing the pipeline. The main problem is that `dockers` is considered deprecated, while `dockers_v2` is in alpha. Soft only fails on syntax errors.
=> fix: run goreleaser check as soft
