cmd/dev/pop/migration/render.go

It is now possible to select the database dialects the cli should render. Not specifying the dialects will keep the current behavior of rendering all supported dialects.

feat(pop render): add flag to select dialects

---

cmd/dev/release/notify/draft.go
cmd/dev/release/notify/draft_test.go
cmd/dev/release/publish.go

Also adds documentation for the renamed flag

refactor: rename --from-version to --include-changelog-since

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/semantic.yml
.github/workflows/closed_references.yml
.github/workflows/labels.yml
.github/workflows/stale.yml
.reference-ignore
CONTRIBUTING.md
SECURITY.md

Updated repository templates to https://github.com/ory/meta/commit/5fb2a2c6521ba65d5a26f401b4c4a66fc5dba35b.

chore: update repository template to 5fb2a2c6

---

cmd/dev/newsletter/pkg.go

fix: substr campaignID

---

cmd/dev/schema/render_version.go

fix: skip pre release version schema rendering

---

cmd/dev/newsletter/draft.go
view/mail-body.html

-  reduce content of template <head> to avoid rendering issues
-  add client specific styles to embedded css to avoid rendering issues
-  reduce  embedded styling, a more minimalistic approach works best with all clients
-  change html structure, dont use tables to allow for better responsiveness across devices
-  add ms outlook conditionals

fix: update newsletter styles

---

cmd/dev/newsletter/pkg.go
cmd/dev/newsletter/render_test.go
go.mod
go.sum

the changes.
works.
appropriate).

feat: implement newsletter markdown styling

---

cmd/dev/ci/monorepo/run.go

fix: improve stdout and stderr for ci commands

---

cmd/dev/ci/monorepo/changes.go
cmd/dev/ci/monorepo/components.go
cmd/dev/ci/monorepo/depgraph.go
cmd/dev/ci/monorepo/run.go

In order to understand why a component is flagged as being changed, involved, affected it would be great to get more detailed information on how the cli ended up with the verdict ;)
Add more extensive logging to the debug flag.
the changes.
works.
appropriate).

feat: enhanced debug messages

---

cmd/cloud/proxy/proxy.go
cmd/cloud/remote/client.go
go.mod
go.sum

the changes.
works.
appropriate).

Improve API Key handling and return to logic

---

cmd/dev/ci/orbs/bump.go

the changes.
works.
appropriate).

feat: add ory/prettier to orb updater

---

cmd/dev/main.go
cmd/dev/openapi/main.go
cmd/dev/openapi/migrate.go
go.mod
go.sum

the changes.
works.
appropriate).

feat: add openapi tools

---

cmd/cloud/proxy/proxy.go

the changes.
works.
appropriate).

feat: add logging to upstream calls

---

cmd/cloud/proxy/proxy.go
cmd/cloud/proxy/proxy_test.go
cmd/dev/newsletter/pkg.go
cmd/dev/openapi/migrate.go
cmd/dev/pop/migration/fizzxlegacy/file_migrator.go
cmd/root.go
cmd/version.go
x/home.go

the changes.
works.
appropriate).

fix: use inclusion instead of exclusion for proxy

---

cmd/dev/openapi/migrate.go
cmd/pkg/patch.go

the changes.
works.
appropriate).

feat: expose oas render patch method

---

cmd/cloud/proxy/main.go
cmd/cloud/proxy/proxy_local.go
cmd/cloud/proxy/proxy_local_test.go
cmd/root.go

the changes.
works.
appropriate).

feat: move proxy command to `ory proxy local` and add UX improvements

---

cmd/cloud/proxy/proxy_local.go
cmd/cloud/proxy/proxy_local_test.go

the changes.
works.
appropriate).

fix: use correct redirect url

---

cmd/cloud/proxy/proxy_local.go

the changes.
works.
appropriate).

fix: example command

---

cmd/dev/pop/migration/fizzx/migrator.go

The problem occurred where you would have one "all" migration that is only overwritten with one flavored migration, e.g.
```
1_foo.up.sql
1_foo.mysql.up.sql
1_foo.down.sql
```
The migrations are already sorted correctly, so just not running the "all" migration if there was already a specific one fixes it.

fix: keep track of what migrations are already run

---

cmd/cloud/proxy/common.go

the changes.
works.
appropriate).

feat: rewrite body for the urls

---

npm/index.js

the changes.
works.
appropriate).

fix: workaround for apple silicon

---

cmd/dev/release/publish.go

Closes https://github.com/ory/kratos/issues/1738
the changes.
works.
appropriate).

feat: run docs generation as part of release pipeline

---

cmd/dev.go
cmd/dev/schema/render_version.go
cmd/dev/schema/render_version_test.go
cmd/nodev.go
go_mod_version_pins.go

closes https://github.com/ory/hydra/issues/2748
the changes.
works.
appropriate).

fix: skip pre-releases of matured projects as well

---

.github/workflows/cve-scan.yaml
Dockerfile-build
Makefile

- Introduce cve scanning pipeline
- Add dockerfile-build
- Fix makefile target
- Bump alpine images
the changes.
works.
appropriate).

feat: introduce cve scanning

---

cmd/dev/release/publish.go
cmd/pkg/repos.go

In Keto we have hierarchical tags, that should be ignored when searching for the latest version. This adds a way to configure this.
Example tag https://github.com/ory/keto/releases/tag/proto%2Fv0.6.0-alpha.3
the changes.
works.
appropriate).

feat: allow ignoring tags based on a pattern

---

cmd/dev/release/publish.go

Failing CI: https://app.circleci.com/pipelines/github/ory/keto/1542/workflows/e3dd2c93-1129-4175-bba3-d0679315f342/jobs/9949

fix: run format after docusaurus

---

.circleci/config.yml
.goreleaser.yml
Dockerfile
buildinfo/version.go
cmd/cloud/proxy/common.go
cmd/version.go
x/version.go

the changes.
works.
appropriate).

feat: add apple silicon support

---

cmd/dev/release/publish.go
go.mod

the changes.
works.
appropriate).

fix: remove tag management on release

---

cmd/dev/pop/migration/create.go

the changes.
works.
appropriate).

fix: inverted has predicate

---

cmd/dev/pop/migration/render.go

the changes.
works.
appropriate).

feat: replace removes old migration dir

---

cmd/dev/newsletter/pkg.go

Looks like I missed this in the previous PR! 😬

fix: fallback to GitHub in campaignID func

---

cmd/cloud/proxy/common.go

Resolves issue #144 
the changes.
works.
appropriate).

feat: add key ID header to JWT signer

---

cmd/pkg/git.go

If answer is not `n`, we simply call `Confirm` again. Looks like this:
```
Are you sure you want to proceed without creating a pre version first? [y/n] x
Are you sure you want to proceed without creating a pre version first? [y/n] q
Are you sure you want to proceed without creating a pre version first? [y/n] z
Are you sure you want to proceed without creating a pre version first? [y/n] n
Aborting because your answer was: n
```
#133 
the changes.
works.
appropriate).

fix: abort on 'n', retry otherwise

---

.github/workflows/cve-scan.yaml
.grype.yaml

the changes.
works.
appropriate).

ci: ignore invalid cve

---

.github/workflows/ci.yaml

the changes.
works.
appropriate).

fix: output dir for docs

---

cmd/cloudx/project/get_permission_config.go
cmd/cloudx/project/patch_permission_config.go

the changes.
works.
appropriate).

fix: cli doc format

---

.github/workflows/test-e2e.yml
cmd/cloudx/client/handler_test.go
cmd/cloudx/project/update_test.go
cmd/cloudx/proxy/cmd_proxy.go
cmd/cloudx/proxy/cmd_tunnel.go
cmd/cloudx/proxy/proxy.go

the changes.
works.
appropriate).

fix: improve tunnel/proxy command

---

cmd/cloudx/proxy/cmd_proxy.go
cmd/cloudx/proxy/cmd_tunnel.go

the changes.
works.
appropriate).

feat: add cors to ory proxy

---

go.mod
go.sum

the changes.
works.
appropriate).

fix: broken sdk version

---

.github/workflows/test-e2e.yml
.github/workflows/test.yml
README.md

the changes.
works.
appropriate).

ci: add CI badges to readme

---

cmd/cloudx/client/.snapshots/TestCommandHelper-func=UpdateProject-is_able_to_update_a_project.json
cmd/cloudx/client/handler_test.go
cmd/cloudx/get.go
cmd/cloudx/project/.snapshots/TestUpdateProject-target=identity-config-is_able_to_update_a_project.json
cmd/cloudx/project/.snapshots/TestUpdateProject-target=oauth2-config-is_able_to_update_a_project.json
cmd/cloudx/project/.snapshots/TestUpdateProject-target=project-is_able_to_update_a_project.json
cmd/cloudx/project/fixtures/update-hydra/json/config.json
cmd/cloudx/project/fixtures/update-kratos/json/config.json
cmd/cloudx/project/fixtures/update/json/config.json
cmd/cloudx/project/get_oauth2_config.go
cmd/cloudx/project/get_test.go
cmd/cloudx/project/update_test.go

the changes.
works.
appropriate).

feat: add `get oauth2-config` command

---

cmd/cloudx/e2e/app.js
cmd/cloudx/e2e/cypress/integration/integration.spec.js
cmd/cloudx/e2e/cypress/plugins/index.js
cmd/cloudx/e2e/cypress/support/index.js
cypress/integration/proxy.spec.js
cypress/plugins/index.js
cypress/support/index.js
npm/index.js
package-lock.json
package.json

- updates the format to the latest version
- formats all files
- sorts package.json
the changes.
works.
appropriate).

chore: update format + sort package.json

---

cmd/cloudx/proxy/proxy.go

the changes.
works.
appropriate).

fix: do not use redirect logic in proxy

---

.github/workflows/format.yml
Makefile
cmd/cloudx/e2e/cypress/integration/integration.spec.js
package.json

Addresses parts of https://github.com/ory-corp/general/issues/735.
https://github.com/ory-corp/general/issues/735
the changes.
works.
appropriate).

chore: format using Make

---

cmd/cloudx/oauth2/update.go
cmd/cloudx/oauth2/update_test.go
cmd/cloudx/update.go

Closes #230
the changes.
works.
appropriate).

fix: broken `update clients` command

---

cmd/cloudx/proxy/proxy.go

the changes.
works.
appropriate).

fix: remove stray printf

---

cmd/cloudx/auth.go
cmd/cloudx/client/handler.go
cmd/cloudx/create.go
cmd/cloudx/e2e/README.md
cmd/cloudx/parse.go
cmd/cloudx/project/create.go
cmd/cloudx/project/get.go
cmd/cloudx/project/get_identity_config.go
cmd/cloudx/project/get_oauth2_config.go
cmd/cloudx/project/get_permission_config.go
cmd/cloudx/project/list.go
cmd/cloudx/project/patch.go
cmd/cloudx/project/patch_identity_config.go
cmd/cloudx/project/patch_oauth2_config.go
cmd/cloudx/project/patch_permission_config.go
cmd/cloudx/project/update.go
cmd/cloudx/project/update_identity_config.go
cmd/cloudx/project/update_namespace_config.go
cmd/cloudx/project/update_oauth2_config.go
cmd/cloudx/project/update_permission_config.go
cmd/cloudx/proxy/cmd_proxy.go
cmd/cloudx/proxy/cmd_tunnel.go
cmd/cloudx/proxy/proxy.go

the changes.
works.
appropriate).

feat: rename cloud -> network

---

cmd/dev/headers/license.go
cmd/dev/headers/license_test.go

fixes some technical drift before adding more header functionality

chore: fix technical drift

---

cmd/cloudx/auth.go
cmd/cloudx/auth_test.go
cmd/cloudx/client/handler.go
cmd/cloudx/client/handler_test.go
cmd/cloudx/e2e/README.md
cmd/cloudx/project/create_test.go
cmd/cloudx/project/get.go
cmd/cloudx/project/get_identity_config.go
cmd/cloudx/project/get_oauth2_config.go
cmd/cloudx/project/get_permission_config.go
cmd/cloudx/project/list.go
cmd/cloudx/project/patch.go
cmd/cloudx/project/patch_identity_config.go
cmd/cloudx/project/patch_oauth2_config.go
cmd/cloudx/project/patch_permission_config.go
cmd/cloudx/project/update.go
cmd/cloudx/project/update_identity_config.go
cmd/cloudx/project/update_namespace_config.go
cmd/cloudx/project/update_oauth2_config.go
cmd/cloudx/project/update_permission_config.go
cmd/cloudx/proxy/cmd_proxy.go
cmd/cloudx/proxy/cmd_tunnel.go
cmd/cloudx/proxy/proxy.go
cmd/cloudx/testhelpers/testhelpers.go

the changes.
works.
appropriate).

Fix naming

---

cmd/dev/headers/comments/file_type_test.go
cmd/dev/headers/copyright.go
cmd/dev/headers/copyright_test.go

https://github.com/ory-corp/general/issues/602
the changes.
works.
appropriate).

fix: ignore files in node_modules and files without extension

---

cmd/cloudx/client/print.go

the changes.
works.
appropriate).

chore: fix command spelling

---

cmd/dev/release/publish.go

the changes.
works.
appropriate).

fix: panic in args

---

cmd/dev/ci/deps/url_test.go

the changes.
works.
appropriate).

chore: use error assertions

---

cmd/cloudx/client/.snapshots/TestCommandHelper-func=UpdateProject-is_able_to_update_a_project.json
cmd/cloudx/client/fixtures/update_project/config.json

the changes.
works.
appropriate).

chore: update snapshots

---

cmd/cloudx/proxy/proxy.go

#271 
the changes.
works.
appropriate).

feat: fix tunnel

---

cmd/cloudx/proxy/cmd_proxy.go
cmd/cloudx/proxy/cmd_tunnel.go

Updates the tunnel and proxy description to inform users about setting a custom ui base url on their custom domain when using a custom domain with the tunnel/proxy.
related issue: https://github.com/ory/network/issues/218
the changes.
works.
appropriate).

chore: update proxy and tunnel help description

---

cmd/cloudx/client/handler.go

the changes.
works.
appropriate).

fix: error handling when logging in with AAL2

---

.github/workflows/ci.yaml
.gitignore
cmd/cloudx/accountexperience/accountexperience_test.go
cmd/cloudx/client/command_helper_test.go
cmd/cloudx/identity/list_test.go
cmd/cloudx/identity/main_test.go
cmd/cloudx/oauth2/client_test.go
cmd/cloudx/organizations/organizations_test.go
cmd/cloudx/project/create.go
cmd/cloudx/project/create_test.go
cmd/cloudx/project/helper_test.go
cmd/cloudx/project/list_test.go
cmd/cloudx/project/main_test.go
cmd/cloudx/project/update_test.go
cmd/cloudx/project/use_test.go
cmd/cloudx/relationtuples/relationtuples_test.go
cmd/cloudx/testhelpers/testhelpers.go
cmd/cloudx/testhelpers/testmain.go

Require workspace for new projects, as projects without workspaces are deprecated.

feat: require workspace when creating projects

---

cmd/cloudx/client/auth.go
cmd/cloudx/proxy/helpers.go
cmd/cloudx/proxy/proxy.go
cmd/cloudx/proxy/tunnel.go

The `--dev` flag essentially enabled wildcard cors. To make development easier, the flag has been removed and instead we will check if the user supplied specific CORS origins. If they did not, wildcard CORS is enabled.
The Ory Proxy and Ory Tunnel are only supposed to be used during development, so adding a flag `--dev` seemed pointless.
the changes.
works.
appropriate).

feat: tunnel and proxy use dev mode always

---

cmd/cloudx/proxy/proxy.go
cmd/cloudx/proxy/tunnel.go

the changes.
works.
appropriate).

feat: clarify use of tunnel/proxy

---

cmd/cloudx/client/command_helper.go
cmd/cloudx/client/project.go
cmd/cloudx/client/workspace.go
cmd/cloudx/get.go
cmd/cloudx/project/create.go
cmd/cloudx/project/create_test.go
cmd/cloudx/workspace/get.go

feat: allow creating a workspace together with a project

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build
.github/workflows/test-integration.yaml
scripts/hello.sh

the changes.
works.
appropriate).

chore: add gha integration test
